### ISSUE TITLE
[Bug]: nest.js 模板在开启文件系统隔离的server 中，使用 blocklet dev 启动失败报错: Access to this API has been restricted. Permission: process.binding

### ISSUE THREAD

**Issue by skypesky** [blocklet/create-blocklet#338]
- [ ] blocklet dev 执行日志如下: 

```ts

(2024-07-21 17:12:26): node:internal/process/pre_execution:575
(2024-07-21 17:12:26):       throw new ERR_ACCESS_DENIED('process.binding');
(2024-07-21 17:12:26):       ^
(2024-07-21 17:12:26): 
(2024-07-21 17:12:26): Error [ERR_ACCESS_DENIED]: Access to this API has been restricted. Permission: process.binding
(2024-07-21 17:12:26):     at process.binding (node:internal/process/pre_execution:575:13)
(2024-07-21 17:12:26):     at Object.<anonymous> (/Users/skypesky/workSpaces/javascript/arcblock/nest-demo/node_modules/.pnpm/tmp@0.0.33/node_modules/tmp/lib/tmp.js:16:20)
(2024-07-21 17:12:26):     at Module._compile (node:internal/modules/cjs/loader:1434:14)
(2024-07-21 17:12:26):     at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
(2024-07-21 17:12:26):     at Module.load (node:internal/modules/cjs/loader:1249:32)
(2024-07-21 17:12:26):     at Module._load (node:internal/modules/cjs/loader:1065:12)
(2024-07-21 17:12:26):     at Module.require (node:internal/modules/cjs/loader:1271:19)
(2024-07-21 17:12:26):     at require (node:internal/modules/helpers:123:16)
(2024-07-21 17:12:26):     at Object.<anonymous> (/Users/skypesky/workSpaces/javascript/arcblock/nest-demo/node_modules/.pnpm/external-editor@3.1.0/node_modules/external-editor/main/index.js:13:13)
(2024-07-21 17:12:26):     at Module._compile (node:internal/modules/cjs/loader:1434:14) {
(2024-07-21 17:12:26):   code: 'ERR_ACCESS_DENIED'
(2024-07-21 17:12:26): }
(2024-07-21 17:12:26): 
(2024-07-21 17:12:26): Node.js v22.2.0
(2024-07-21 17:12:26): node:internal/process/pre_execution:575
(2024-07-21 17:12:26):       throw new ERR_ACCESS_DENIED('process.binding');
(2024-07-21 17:12:26):       ^
(2024-07-21 17:12:26): 
(2024-07-21 17:12:26): Error [ERR_ACCESS_DENIED]: Access to this API has been restricted. Permission: process.binding
(2024-07-21 17:12:26):     at process.binding (node:internal/process/pre_execution:575:13)
(2024-07-21 17:12:26):     at Object.<anonymous> (/Users/skypesky/workSpaces/javascript/arcblock/nest-demo/node_modules/.pnpm/tmp@0.0.33/node_modules/tmp/lib/tmp.js:16:20)
(2024-07-21 17:12:26):     at Module._compile (node:internal/modules/cjs/loader:1434:14)
(2024-07-21 17:12:26):     at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
(2024-07-21 17:12:26):     at Module.load (node:internal/modules/cjs/loader:1249:32)
(2024-07-21 17:12:26):     at Module._load (node:internal/modules/cjs/loader:1065:12)
(2024-07-21 17:12:26):     at Module.require (node:internal/modules/cjs/loader:1271:19)
(2024-07-21 17:12:26):     at require (node:internal/modules/helpers:123:16)
(2024-07-21 17:12:26):     at Object.<anonymous> (/Users/skypesky/workSpaces/javascript/arcblock/nest-demo/node_modules/.pnpm/external-editor@3.1.0/node_modules/external-editor/main/index.js:13:13)
(2024-07-21 17:12:26):     at Module._compile (node:internal/modules/cjs/loader:1434:14) {
(2024-07-21 17:12:26):   code: 'ERR_ACCESS_DENIED'
(2024-07-21 17:12:26): }
(2024-07-21 17:12:26): 
(2024-07-21 17:12:26): Node.js v22.2.0
(2024-07-21 17:12:27): node:internal/process/pre_execution:575
(2024-07-21 17:12:27):       throw new ERR_ACCESS_DENIED('process.binding');
(2024-07-21 17:12:27):       ^
(2024-07-21 17:12:27): 
(2024-07-21 17:12:27): Error [ERR_ACCESS_DENIED]: Access to this API has been restricted. Permission: process.binding
(2024-07-21 17:12:27):     at process.binding (node:internal/process/pre_execution:575:13)
(2024-07-21 17:12:27):     at Object.<anonymous> (/Users/skypesky/workSpaces/javascript/arcblock/nest-demo/node_modules/.pnpm/tmp@0.0.33/node_modules/tmp/lib/tmp.js:16:20)
(2024-07-21 17:12:27):     at Module._compile (node:internal/modules/cjs/loader:1434:14)
(2024-07-21 17:12:27):     at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
(2024-07-21 17:12:27):     at Module.load (node:internal/modules/cjs/loader:1249:32)
(2024-07-21 17:12:27):     at Module._load (node:internal/modules/cjs/loader:1065:12)
(2024-07-21 17:12:27):     at Module.require (node:internal/modules/cjs/loader:1271:19)
(2024-07-21 17:12:27):     at require (node:internal/modules/helpers:123:16)
(2024-07-21 17:12:27):     at Object.<anonymous> (/Users/skypesky/workSpaces/javascript/arcblock/nest-demo/node_modules/.pnpm/external-editor@3.1.0/node_modules/external-editor/main/index.js:13:13)
(2024-07-21 17:12:27):     at Module._compile (node:internal/modules/cjs/loader:1434:14) {
(2024-07-21 17:12:27):   code: 'ERR_ACCESS_DENIED'
(2024-07-21 17:12:27): }
(2024-07-21 17:12:27): 
(2024-07-21 17:12:27): Node.js v22.2.0
(2024-07-21 17:12:28): node:internal/process/pre_execution:575
(2024-07-21 17:12:28):       throw new ERR_ACCESS_DENIED('process.binding');
(2024-07-21 17:12:28):       ^
(2024-07-21 17:12:28): 
(2024-07-21 17:12:28): Error [ERR_ACCESS_DENIED]: Access to this API has been restricted. Permission: process.binding
(2024-07-21 17:12:28):     at process.binding (node:internal/process/pre_execution:575:13)
(2024-07-21 17:12:28):     at Object.<anonymous> (/Users/skypesky/workSpaces/javascript/arcblock/nest-demo/node_modules/.pnpm/tmp@0.0.33/node_modules/tmp/lib/tmp.js:16:20)
(2024-07-21 17:12:28):     at Module._compile (node:internal/modules/cjs/loader:1434:14)
(2024-07-21 17:12:28):     at Module._extensions..js (node:internal/modules/cjs/loader:1518:10)
(2024-07-21 17:12:28):     at Module.load (node:internal/modules/cjs/loader:1249:32)
(2024-07-21 17:12:28):     at Module._load (node:internal/modules/cjs/loader:1065:12)
(2024-07-21 17:12:28):     at Module.require (node:internal/modules/cjs/loader:1271:19)
(2024-07-21 17:12:28):     at require (node:internal/modules/helpers:123:16)
(2024-07-21 17:12:28):     at Object.<anonymous> (/Users/skypesky/workSpaces/javascript/arcblock/nest-demo/node_modules/.pnpm/external-editor@3.1.0/node_modules/external-editor/main/index.js:13:13)
(2024-07-21 17:12:28):     at Module._compile (node:internal/modules/cjs/loader:1434:14) {
(2024-07-21 17:12:28):   code: 'ERR_ACCESS_DENIED'
(2024-07-21 17:12:28): }
(2024-07-21 17:12:28): 
(2024-07-21 17:12:28): Node.js v22.2.0
✖ blocklet-project@0.1.0 start failed for blocklet-project: z2qaD7sw3bdXPpUKAKLetonLH58hXpvdzF2NH/z2qaD7sw3bdXPpUKAKLetonLH58hXpvdzF2NH is not running within 3 seconds

Disconnecting from Blocklet Server daemon....
Component blocklet-project was removed
```

related: https://github.com/ArcBlock/hiring/issues/968

**Comment by skypesky** [comment]
定位到 tmp 这个包报错了,使用 pnpm why tmp 发现是 @nestjs/cli, 锁定 tmp 到最新版本即可解决
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/c605d9ca-e368-4086-9d27-dbb47d211baa">

**Comment by skypesky** [comment]
- [ ] 有空的时候，需要提交一个 issue 给 @nestjs/cli，让他们升级的 tmp
